### ISSUE TITLE
Cloning this Repository

### ISSUE THREAD

**Issue by JohnWilliamsArtist** [tilix/jw-artist#48]

**Comment by JohnWilliamsArtist** [comment]
@drnw if I clone this repository does that mean I have to work on it on my desktop using Github desktop?
Because I have 10.7.5 OS and I need 10.9 to run Github desktop

Please advise,

John

**Comment by drnw** [comment]
You want to Fork rather than clone…

[cid:07D10606-7218-471D-B53C-D03C3B96682C]

On 22 Oct 2017, at 19:29, John Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


@drnw<https://github.com/drnw> if I clone this repository does that mean I have to work on it on my desktop using Github desktop?
Because I have 10.7.5 OS and I need 10.9 to run Github desktop

Please advise,

John

**Comment by JohnWilliamsArtist** [comment]
cheers, thanks for the tip :-)
